### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [Jeroen0601/0701_Capstone#5]
Your code base is amazing but the visual side could use some work. There are some improvements you can make like changing the color scheme and fixing some spacing issues that can make this project look a lot better!

++ Consistency with indentations and whitespace.
++ Addition of comments.
++ Mobile version present.
++ Organized file tree.

-- Spacing needed.
-- Viewport meta tag missing.
-- Personal touches would've been a great addition.

Overall, great work!

Grade: Meets expectation.

**Comment by Jeroen0601** [comment]
Thanks.
